[package]
name = 'openid'
version = '0.1.0'
authors = ['Alexander Korolev <kilork@yandex.ru>']
edition = '2018'
categories = []
description = '''
openid description.
'''
homepage = 'https://github.com/kilork/openid'
keywords = [
    'authentication',
    'authorization',
    'auth',
    'oauth',
    'openid',
]
license = 'Unlicense OR MIT'
readme = 'README.md'
repository = 'https://github.com/kilork/openid'

[dependencies]
lazy_static = '1.4'
serde_json = '1'
base64 = '0.11'
biscuit = '0.4'
failure = '0.1'

[dependencies.url]
version = '2.1'

[dependencies.chrono]
version = '0.4'
features = ['serde']

[dependencies.serde]
version = '1'
features = ['derive']

[dependencies.reqwest]
version = '0.10'
features = ['json']
